services:
  schedulify:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - schedulify

volumes:
  pgdata: